trigger:
  branches:
    include:
    - SPRINT_1
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
    - task: CmdLine@2
      displayName: 'npm install and build'
      inputs:
        script: |
          cd frontend
          npm install
          npm run build

